import { SiteHeader } from '@/components/marketing/SiteHeader';
import { SiteFooter } from '@/components/marketing/SiteFooter';
import Link from 'next/link';

export const metadata = {
    title: 'Terms of Service | Response Audit',
    description: 'Terms of Service for Response Audit — usage agreement, service terms, cancellation policy, and legal disclaimers.',
};

export default function TermsPage() {
    return (
        <div className="min-h-screen bg-[#f8fafc] dark:bg-[#0f172a] text-[#0f172a] dark:text-slate-200 flex flex-col">
            <SiteHeader />

            <main className="container mx-auto max-w-4xl px-6 py-16 flex-1">
                {/* Header */}
                <div className="mb-12 mt-12">
                    <h1 className="text-4xl font-black text-[#0f172a] dark:text-white mb-4 tracking-tight">Terms of Service</h1>
                    <p className="text-slate-500 font-medium">Last updated: March 1, 2026</p>
                    <p className="text-slate-500 text-sm mt-2">
                        Please read these Terms of Service (&quot;Terms&quot;, &quot;Agreement&quot;) carefully before using the Response Audit platform operated by Response Audit (&quot;Company&quot;, &quot;we&quot;, &quot;us&quot;, &quot;our&quot;). By accessing or using the Service, you agree to be bound by these Terms. If you do not agree, you must not use the Service.
                    </p>
                </div>

                {/* Content */}
                <div className="prose prose-slate dark:prose-invert max-w-none">
                    <div className="space-y-8 text-slate-600 dark:text-slate-300 leading-relaxed font-medium">

                        <section className="bg-white dark:bg-slate-900 p-8 rounded-3xl shadow-md border border-slate-200 dark:border-slate-800">
                            <h2 className="text-2xl font-black text-[#0f172a] dark:text-white mb-4">1. Service Description</h2>
                            <p className="mb-3">
                                Response Audit (&quot;the Service&quot;) provides automated monitoring and diagnostic analysis of publicly accessible customer inquiry channels, including but not limited to website contact forms, email response times, Google Business Profile interactions, and phone call availability.
                            </p>
                            <p className="mb-3">
                                Our service operates by interacting only with <strong>publicly available endpoints</strong>. We do not access, intercept, or monitor private communications, internal systems, employee data, or confidential business information.
                            </p>
                            <p>
                                The diagnostic reports, scores, recommendations, and insights generated by the Service are <strong>informational in nature</strong> and are intended as operational guidance. They do not constitute professional consulting, legal advice, financial advice, or any form of guaranteed business outcome.
                            </p>
                        </section>

                        <section className="bg-white dark:bg-slate-900 p-8 rounded-3xl shadow-md border border-slate-200 dark:border-slate-800">
                            <h2 className="text-2xl font-black text-[#0f172a] dark:text-white mb-4">2. Account Registration & Eligibility</h2>
                            <ul className="list-disc pl-6 space-y-2">
                                <li>You must be at least 18 years of age and have the legal authority to enter into this Agreement.</li>
                                <li>You must provide accurate, current, and complete information during registration and keep it updated.</li>
                                <li>You are solely responsible for maintaining the confidentiality of your account credentials.</li>
                                <li>You are responsible for all activities that occur under your account, whether or not authorized by you.</li>
                                <li>You must notify us immediately of any unauthorized use of your account at <a href="mailto:support@responseaudit.com" className="text-primary hover:text-blue-700 font-bold">support@responseaudit.com</a>.</li>
                                <li>One account per individual or business entity. Multiple accounts created to circumvent restrictions may be terminated.</li>
                            </ul>
                        </section>

                        <section className="bg-white dark:bg-slate-900 p-8 rounded-3xl shadow-md border border-slate-200 dark:border-slate-800">
                            <h2 className="text-2xl font-black text-[#0f172a] dark:text-white mb-4">3. Acceptable Use Policy</h2>
                            <p className="mb-4">By using the Service, you agree that you will NOT:</p>
                            <ul className="list-disc pl-6 space-y-2">
                                <li>Use the Service for any unlawful, fraudulent, or malicious purpose</li>
                                <li>Monitor businesses you do not own or have authorization to audit</li>
                                <li>Attempt to reverse-engineer, decompile, or extract source code from our systems</li>
                                <li>Interfere with, disrupt, or overload the Service infrastructure</li>
                                <li>Use automated tools (bots, scrapers) to access the Service beyond its intended functionality</li>
                                <li>Resell, sublicense, or redistribute the Service or any reports generated by it without written consent</li>
                                <li>Use the Service to harass, defame, or harm any third party</li>
                                <li>Transmit viruses, malware, or any harmful code through the Service</li>
                            </ul>
                            <p className="mt-4 text-sm text-slate-500 dark:text-slate-400">
                                Violation of this policy may result in immediate account suspension or termination without notice or refund.
                            </p>
                        </section>

                        <section className="bg-white dark:bg-slate-900 p-8 rounded-3xl shadow-md border border-slate-200 dark:border-slate-800">
                            <h2 className="text-2xl font-black text-[#0f172a] dark:text-white mb-4">4. Service Limitations & No Guarantees</h2>
                            <ul className="list-disc pl-6 space-y-2">
                                <li>Our diagnostic tests simulate customer inquiries and <strong>may trigger actual responses</strong> from your contact channels.</li>
                                <li>Results are generated using automated algorithms and are provided <strong>&quot;as-is&quot; without guarantee of accuracy, completeness, or fitness for any particular purpose</strong>.</li>
                                <li>We do not guarantee any specific business outcome, revenue increase, lead recovery, or operational improvement as a result of using the Service.</li>
                                <li>We cannot monitor private or internal communication channels.</li>
                                <li>Service availability is targeted at 99.5% monthly uptime but is not guaranteed. Scheduled maintenance windows are excluded.</li>
                                <li>Features, functionality, and user interface may change at any time as part of ongoing product development.</li>
                            </ul>
                        </section>

                        <section className="bg-white dark:bg-slate-900 p-8 rounded-3xl shadow-md border border-slate-200 dark:border-slate-800">
                            <h2 className="text-2xl font-black text-[#0f172a] dark:text-white mb-4">5. Subscription & Payment Terms</h2>
                            <ul className="list-disc pl-6 space-y-3">
                                <li>All subscriptions are billed on a <strong>monthly recurring basis</strong> through PayPal.</li>
                                <li>Your billing cycle begins on the date of your first successful payment and renews automatically every 30 days.</li>
                                <li>By subscribing, you authorize recurring charges to your PayPal account until you cancel.</li>
                                <li>You will receive an email confirmation from PayPal for each payment processed.</li>
                                <li>Pricing is as listed on our <a href="/pricing" className="text-primary hover:text-blue-700 font-bold">Pricing page</a> at the time of subscription. We will notify you at least 15 days in advance of any pricing changes.</li>
                                <li>All payments are processed securely via PayPal. Response Audit does not store your payment card or banking details.</li>
                                <li>Failed payments may result in temporary service suspension. You will be notified and given a reasonable grace period to resolve payment issues.</li>
                            </ul>
                        </section>

                        <section className="bg-white dark:bg-slate-900 p-8 rounded-3xl shadow-md border border-blue-200 dark:border-blue-800/50">
                            <h2 className="text-2xl font-black text-[#0f172a] dark:text-white mb-4">6. Cancellation & Refund Policy</h2>
                            <p className="mb-4">
                                We believe in earning your business every month. Our cancellation policy is designed to be straightforward, fair, and transparent:
                            </p>
                            <div className="space-y-4 mb-6">
                                <div className="bg-slate-50 dark:bg-slate-800/50 p-4 rounded-xl border border-slate-200 dark:border-slate-700">
                                    <h3 className="font-bold text-[#0f172a] dark:text-white mb-2">📋 Cancel Anytime</h3>
                                    <p>You may cancel your subscription at any time directly from your dashboard settings or by contacting our support team. No questions asked, no cancellation fees, no penalties, and no lengthy processes.</p>
                                </div>
                                <div className="bg-slate-50 dark:bg-slate-800/50 p-4 rounded-xl border border-slate-200 dark:border-slate-700">
                                    <h3 className="font-bold text-[#0f172a] dark:text-white mb-2">✅ Service Until End of Billing Cycle</h3>
                                    <p>Upon cancellation, your subscription remains active and you continue to have full access to all features and reports until the end of your current paid billing period. We do not cut off access early.</p>
                                </div>
                                <div className="bg-slate-50 dark:bg-slate-800/50 p-4 rounded-xl border border-slate-200 dark:border-slate-700">
                                    <h3 className="font-bold text-[#0f172a] dark:text-white mb-2">🚫 No Charges After Cancellation</h3>
                                    <p>Once cancelled, <strong>absolutely no further payments will be deducted</strong> from your account. Your recurring billing is terminated immediately upon cancellation request, and you will not be charged for any subsequent billing cycles.</p>
                                </div>
                                <div className="bg-slate-50 dark:bg-slate-800/50 p-4 rounded-xl border border-slate-200 dark:border-slate-700">
                                    <h3 className="font-bold text-[#0f172a] dark:text-white mb-2">💰 No Refund Policy</h3>
                                    <p>Due to the nature of our digital diagnostic services, the instant delivery of reports, and the costs associated with third-party payment processing (including international transaction fees), <strong>all sales are final and we do not offer refunds</strong> for any completed or partially completed billing period. This applies to all subscription plans without exception.</p>
                                </div>
                            </div>
                            <p className="text-sm text-slate-500 dark:text-slate-400 italic">
                                We strongly encourage all prospective subscribers to thoroughly review our service features, examine the free audit results, and take advantage of the free audit tool before subscribing to ensure Response Audit is the right fit for your business needs.
                            </p>
                        </section>

                        <section className="bg-white dark:bg-slate-900 p-8 rounded-3xl shadow-md border border-slate-200 dark:border-slate-800">
                            <h2 className="text-2xl font-black text-[#0f172a] dark:text-white mb-4">7. Intellectual Property</h2>
                            <p className="mb-3">
                                All content, features, functionality, software, algorithms, designs, trademarks, logos, and service names of Response Audit are the exclusive property of the Company and are protected by international copyright, trademark, patent, trade secret, and other intellectual property laws.
                            </p>
                            <ul className="list-disc pl-6 space-y-2">
                                <li>You may not copy, modify, distribute, sell, or lease any part of the Service.</li>
                                <li>You may not use our branding, logos, or trademarks without prior written consent.</li>
                                <li>You retain ownership of your business data. We retain ownership of all diagnostic algorithms, scoring methodologies, and aggregated analytical insights.</li>
                                <li>We reserve the right to use anonymized, aggregated data derived from the Service for product improvement, research, and marketing purposes.</li>
                            </ul>
                        </section>

                        <section className="bg-white dark:bg-slate-900 p-8 rounded-3xl shadow-md border border-red-200 dark:border-red-800/30">
                            <h2 className="text-2xl font-black text-[#0f172a] dark:text-white mb-4">8. Limitation of Liability</h2>
                            <p className="mb-3">
                                <strong>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW:</strong>
                            </p>
                            <ul className="list-disc pl-6 space-y-3">
                                <li>The Service is provided on an <strong>&quot;AS IS&quot;</strong> and <strong>&quot;AS AVAILABLE&quot;</strong> basis without warranties of any kind, whether express, implied, statutory, or otherwise, including but not limited to implied warranties of merchantability, fitness for a particular purpose, title, and non-infringement.</li>
                                <li>In no event shall the Company, its directors, employees, partners, agents, suppliers, or affiliates be liable for any <strong>indirect, incidental, special, consequential, or punitive damages</strong>, including without limitation: loss of profits, data, revenue, goodwill, business opportunities, or anticipated savings.</li>
                                <li>Our total aggregate liability for any claims arising from or related to the Service shall not exceed the <strong>amount you paid to us in the three (3) months immediately preceding the event giving rise to the claim</strong>.</li>
                                <li>We are not liable for any decisions you make based on the information, reports, or recommendations provided by the Service.</li>
                                <li>We are not responsible for any third-party services, platforms, or integrations that interact with the Service, including PayPal payment processing.</li>
                            </ul>
                        </section>

                        <section className="bg-white dark:bg-slate-900 p-8 rounded-3xl shadow-md border border-slate-200 dark:border-slate-800">
                            <h2 className="text-2xl font-black text-[#0f172a] dark:text-white mb-4">9. Indemnification</h2>
                            <p>
                                You agree to defend, indemnify, and hold harmless the Company, its officers, directors, employees, contractors, agents, licensors, suppliers, successors, and assigns from and against any claims, liabilities, damages, judgments, awards, losses, costs, expenses, or fees (including reasonable legal fees) arising out of or relating to: (a) your violation of these Terms; (b) your use of the Service; (c) your violation of any third-party rights; (d) any content you submit through the Service; or (e) any activity under your account, whether or not authorized by you.
                            </p>
                        </section>

                        <section className="bg-white dark:bg-slate-900 p-8 rounded-3xl shadow-md border border-slate-200 dark:border-slate-800">
                            <h2 className="text-2xl font-black text-[#0f172a] dark:text-white mb-4">10. Account Termination</h2>
                            <ul className="list-disc pl-6 space-y-2">
                                <li>We reserve the right to suspend or terminate your account at our sole discretion, with or without notice, for any reason, including but not limited to: violation of these Terms, abusive behavior, non-payment, or suspected fraudulent activity.</li>
                                <li>You may terminate your account at any time from the dashboard settings or by emailing us.</li>
                                <li>Upon termination, your right to use the Service ceases immediately.</li>
                                <li>Your diagnostic data will be retained for 30 days post-termination in case you wish to reactivate. After 30 days, all data is permanently and irreversibly deleted.</li>
                                <li>Termination does not entitle you to any refund of amounts already paid.</li>
                            </ul>
                        </section>

                        <section className="bg-white dark:bg-slate-900 p-8 rounded-3xl shadow-md border border-slate-200 dark:border-slate-800">
                            <h2 className="text-2xl font-black text-[#0f172a] dark:text-white mb-4">11. Dispute Resolution</h2>
                            <p className="mb-3">
                                In the event of any dispute, claim, or controversy arising out of or relating to these Terms or the Service:
                            </p>
                            <ul className="list-disc pl-6 space-y-2">
                                <li><strong>Informal Resolution First:</strong> You agree to first attempt to resolve the dispute informally by contacting us at <a href="mailto:support@responseaudit.com" className="text-primary hover:text-blue-700 font-bold">support@responseaudit.com</a>. We will work in good faith to resolve your concern within 30 business days.</li>
                                <li><strong>Binding Arbitration:</strong> If informal resolution is unsuccessful, the dispute shall be resolved through binding arbitration in accordance with the rules of the arbitration body in the jurisdiction of the Company. The arbitration shall be conducted in English.</li>
                                <li><strong>Class Action Waiver:</strong> You agree that any dispute resolution proceedings will be conducted only on an individual basis and not in a class, consolidated, or representative action. You waive any right to participate in class actions.</li>
                                <li><strong>Small Claims Exception:</strong> Either party may bring an individual action in small claims court for disputes within that court&apos;s jurisdiction.</li>
                            </ul>
                        </section>

                        <section className="bg-white dark:bg-slate-900 p-8 rounded-3xl shadow-md border border-slate-200 dark:border-slate-800">
                            <h2 className="text-2xl font-black text-[#0f172a] dark:text-white mb-4">12. Force Majeure</h2>
                            <p>
                                The Company shall not be liable for any failure or delay in performing its obligations under these Terms due to causes beyond its reasonable control, including but not limited to: natural disasters, pandemics, government actions, war, terrorism, riots, embargoes, acts of civil or military authorities, fire, floods, accidents, strikes, power outages, internet service provider failures, cyberattacks, or shortages of transportation, facilities, fuel, energy, labor, or materials.
                            </p>
                        </section>

                        <section className="bg-white dark:bg-slate-900 p-8 rounded-3xl shadow-md border border-slate-200 dark:border-slate-800">
                            <h2 className="text-2xl font-black text-[#0f172a] dark:text-white mb-4">13. Modifications to Terms</h2>
                            <p>
                                We reserve the right to modify these Terms at any time. If we make material changes, we will notify you by email or by posting a notice on the Service at least 15 days before the changes take effect. Your continued use of the Service after changes become effective constitutes your acceptance of the revised Terms. If you disagree with the changes, you must stop using the Service and cancel your subscription.
                            </p>
                        </section>

                        <section className="bg-white dark:bg-slate-900 p-8 rounded-3xl shadow-md border border-slate-200 dark:border-slate-800">
                            <h2 className="text-2xl font-black text-[#0f172a] dark:text-white mb-4">14. Governing Law & Jurisdiction</h2>
                            <p>
                                These Terms shall be governed by and construed in accordance with the laws of the jurisdiction in which the Company is registered, without regard to its conflict of law provisions. Any legal action or proceeding arising under these Terms shall be brought exclusively in the courts located in the Company&apos;s jurisdiction, and you consent to personal jurisdiction and venue in such courts.
                            </p>
                        </section>

                        <section className="bg-white dark:bg-slate-900 p-8 rounded-3xl shadow-md border border-slate-200 dark:border-slate-800">
                            <h2 className="text-2xl font-black text-[#0f172a] dark:text-white mb-4">15. Severability & Entire Agreement</h2>
                            <ul className="list-disc pl-6 space-y-2">
                                <li><strong>Severability:</strong> If any provision of these Terms is found to be unenforceable or invalid by a court of competent jurisdiction, such provision shall be limited or eliminated to the minimum extent necessary so that these Terms shall otherwise remain in full force and effect.</li>
                                <li><strong>Entire Agreement:</strong> These Terms, together with the <Link href="/privacy" className="text-primary hover:text-blue-700 font-bold">Privacy Policy</Link>, constitute the entire agreement between you and the Company regarding the Service, and supersede all prior agreements, understandings, negotiations, and discussions, whether oral or written.</li>
                                <li><strong>No Waiver:</strong> The failure of the Company to exercise or enforce any right or provision of these Terms shall not constitute a waiver of such right or provision.</li>
                                <li><strong>Assignment:</strong> You may not assign or transfer these Terms or your rights hereunder without our prior written consent. We may assign our rights and obligations under these Terms without restriction.</li>
                            </ul>
                        </section>

                        <section className="bg-white dark:bg-slate-900 p-8 rounded-3xl shadow-md border border-slate-200 dark:border-slate-800">
                            <h2 className="text-2xl font-black text-[#0f172a] dark:text-white mb-4">16. Contact Information</h2>
                            <p className="mb-4">
                                For questions, concerns, or complaints about these Terms, billing, cancellations, or the Service, contact us at:
                            </p>
                            <div className="bg-slate-50 dark:bg-slate-800/50 p-4 rounded-xl border border-slate-200 dark:border-slate-700 space-y-2">
                                <p><strong>Response Audit</strong></p>
                                <p>Email: <a href="mailto:support@responseaudit.com" className="text-primary hover:text-blue-700 font-bold">support@responseaudit.com</a></p>
                                <p>Legal: <a href="mailto:legal@responseaudit.com" className="text-primary hover:text-blue-700 font-bold">legal@responseaudit.com</a></p>
                            </div>
                        </section>

                    </div>
                </div>
            </main>

            <SiteFooter />
        </div>
    );
}
