import { DiagnosticLog, Gap, GapSeverity } from '../../types';

// 1. CONFIDENCE & TRUST LAYER
export interface TransparencyLogEntry {
    timestamp: Date;
    businessId: string;
    channel: string;
    observation: string;
    confidence: 'LOW' | 'MEDIUM' | 'HIGH';
    isFalsePositiveRisk: boolean;
}

export class TransparencyLogger {
    private logs: TransparencyLogEntry[] = [];

    logObservation(log: DiagnosticLog, confidence: 'LOW' | 'MEDIUM' | 'HIGH') {
        const entry: TransparencyLogEntry = {
            timestamp: new Date(),
            businessId: log.businessId,
            channel: log.channel,
            observation: log.evidence,
            confidence,
            isFalsePositiveRisk: confidence === 'LOW'
        };
        console.log(`[SYSTEM 12] Transparency Log: [${entry.confidence}] ${entry.observation}`);
        this.logs.push(entry);
        return entry;
    }

    getLogs(businessId: string) {
        return this.logs.filter(l => l.businessId === businessId);
    }
}

// 4. CHURN PREVENTION & SILENCE DETECTION
export class ChurnMonitor {
    checkEngagement(businessId: string, lastInteractionDate: Date): string | null {
        const daysSince = (new Date().getTime() - lastInteractionDate.getTime()) / (1000 * 3600 * 24);

        if (daysSince > 30) {
            console.log(`[SYSTEM 12] Silence Detected for ${businessId} (${Math.floor(daysSince)} days).`);
            return "Value Reminder: 3 issues prevented in the last month."; // Value based, not needy
        }
        return null;
    }
}

// 5. LEGAL DISCLAIMER ENGINE
export class DisclaimerEngine {
    appendDisclaimer(content: string): string {
        const disclaimer = `\n\n[DISCLAIMER] These observations are informational and based on publicly observable behavior. They are not guarantees or professional advice.`;
        return content + disclaimer;
    }
}

// 6. CONSENT & EXIT ENFORCER
export class ConsentManager {
    private static optedOutBusinesses: Set<string> = new Set();

    optOut(businessId: string) {
        console.log(`[SYSTEM 12] Business ${businessId} OPTED OUT.`);
        ConsentManager.optedOutBusinesses.add(businessId);
    }

    canMonitor(businessId: string): boolean {
        if (ConsentManager.optedOutBusinesses.has(businessId)) {
            console.log(`[SYSTEM 12] BLOCKING monitor for ${businessId} (Opted Out)`);
            return false;
        }
        return true;
    }
}

// 7. COST & RESOURCE CONTROLLER
export class CostController {
    checkResourceLimits(actionType: 'DIAGNOSTIC' | 'GENERATION'): boolean {
        // Mock logic: Always allow for now, but log usage
        console.log(`[SYSTEM 12] Resource Check for ${actionType}: APPROVED (High Margin Rule Applied)`);
        return true;
    }
}

// 8. SYSTEM IDENTITY PRIMITIVE
export class IdentityManager {
    readonly SYSTEM_SIGNATURE = "\n\n--\nGenerated by Automated Operational Monitoring System.\nReference ID: ";

    signOutput(content: string, refId: string): string {
        return content + this.SYSTEM_SIGNATURE + refId;
    }
}

// 9. DATA LIFECYCLE & RETENTION
export class LifecycleManager {
    private readonly LOG_RETENTION_DAYS = 60;

    checkRetentionPolicy(logDate: Date): boolean {
        const daysOld = (Date.now() - logDate.getTime()) / (1000 * 3600 * 24);
        if (daysOld > this.LOG_RETENTION_DAYS) {
            console.log(`[SYSTEM 12] Log from ${logDate.toISOString()} is EXPIRING (>${this.LOG_RETENTION_DAYS} days). Mock delete.`);
            return false; // Should be deleted
        }
        return true; // Keep
    }
}

// 10. SAFEGUARD ENGINE (HARDENED)
export class SafeguardEngine {
    shouldAlert(gap: Gap, confidenceScore: number): boolean {
        // STRICT THRESHOLD: 0.8
        if (confidenceScore < 0.8) {
            console.log(`[SYSTEM 12] SAFEGUARD BLOCKED alert for Gap ${gap.title}. Confidence ${confidenceScore} < 0.8.`);
            return false;
        }
        return true;
    }
}
